apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: sjf
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/stevef1uk/sjf:latest 
            imagePullPolicy: Always
            env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "6000"
            - name: CASSANDRA_SERVICE_HOST
              value: "glusterfs-dynamic-data-cassandra-0"

