// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/stevef1uk/sjf/models"
)

// GetAccountsOKCode is the HTTP code returned for type GetAccountsOK
const GetAccountsOKCode int = 200

/*GetAccountsOK A list of records

swagger:response getAccountsOK
*/
type GetAccountsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.GetAccountsOKBodyItems `json:"body,omitempty"`
}

// NewGetAccountsOK creates GetAccountsOK with default headers values
func NewGetAccountsOK() *GetAccountsOK {

	return &GetAccountsOK{}
}

// WithPayload adds the payload to the get accounts o k response
func (o *GetAccountsOK) WithPayload(payload []*models.GetAccountsOKBodyItems) *GetAccountsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get accounts o k response
func (o *GetAccountsOK) SetPayload(payload []*models.GetAccountsOKBodyItems) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAccountsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.GetAccountsOKBodyItems, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetAccountsBadRequestCode is the HTTP code returned for type GetAccountsBadRequest
const GetAccountsBadRequestCode int = 400

/*GetAccountsBadRequest Record not found

swagger:response getAccountsBadRequest
*/
type GetAccountsBadRequest struct {
}

// NewGetAccountsBadRequest creates GetAccountsBadRequest with default headers values
func NewGetAccountsBadRequest() *GetAccountsBadRequest {

	return &GetAccountsBadRequest{}
}

// WriteResponse to the client
func (o *GetAccountsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

/*GetAccountsDefault Sorry something went wrong

swagger:response getAccountsDefault
*/
type GetAccountsDefault struct {
	_statusCode int
}

// NewGetAccountsDefault creates GetAccountsDefault with default headers values
func NewGetAccountsDefault(code int) *GetAccountsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetAccountsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get accounts default response
func (o *GetAccountsDefault) WithStatusCode(code int) *GetAccountsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get accounts default response
func (o *GetAccountsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *GetAccountsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
